const chat={scope:'',selected:null,request:0,drafts:new Map(),sending:false,before:null,lastSignature:''};
const chatEl=id=>document.getElementById(id);
const chatScope=()=>session?[session.room,session.role,session.name].join(':'):'';
const chatCall=(action,extra={})=>call({action,room:session.room,token:session.token,...extra});
function chatRemember(){if(chat.selected)chat.drafts.set(chat.selected,chatEl('chatComposer').value);}
function chatReset(){const scope=chatScope();if(scope===chat.scope)return;chat.scope=scope;chat.selected=null;chat.before=null;chat.request++;chat.drafts.clear();chat.lastSignature='';chatEl('chatComposer').value='';chatEl('chatMessages').replaceChildren();}
function chatRender(data){
 const changed=chat.selected!==data.selected;if(changed){chatRemember();chat.selected=data.selected;chatEl('chatComposer').value=chat.drafts.get(chat.selected)||'';}
 chatEl('chatCreate').hidden=!data.canManage;
 const list=chatEl('chatConversations');list.replaceChildren();
 for(const kind of ['channel','dm']){const heading=document.createElement('h4');heading.textContent=kind==='channel'?'ROOM CHANNELS':'DIRECT MESSAGES';list.append(heading);for(const c of data.conversations.filter(c=>c.kind===kind)){const button=document.createElement('button');button.className='chat-conversation'+(c.id===chat.selected?' selected':'');button.textContent=(kind==='channel'?'# ':'')+c.name+(c.managersOnly?' · management':'');button.setAttribute('aria-pressed',String(c.id===chat.selected));button.onclick=()=>{chatRemember();chat.selected=c.id;chat.before=null;chat.lastSignature='';chatEl('chatComposer').value=chat.drafts.get(c.id)||'';chatLoad();};list.append(button);}}
 const select=chatEl('chatPerson'),person=select.value;select.replaceChildren(new Option('Choose someone…',''));for(const p of data.peers)select.add(new Option(`${p.name} · ${p.role}`,p.key));select.value=person;
 chatEl('chatTitle').textContent=data.conversations.find(c=>c.id===chat.selected)?.name||'Room chat';
 const signature=JSON.stringify([chat.selected,data.messages]);if(signature!==chat.lastSignature){const box=chatEl('chatMessages'),atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.replaceChildren();if(!data.messages.length){const empty=document.createElement('p');empty.className='chat-empty';empty.textContent='No messages yet. Start the conversation.';box.append(empty);}for(const m of data.messages){const item=document.createElement('article');item.className='chat-message'+(m.senderKey===data.me?' mine':'');const header=document.createElement('div'),name=document.createElement('strong'),time=document.createElement('time'),body=document.createElement('p');name.textContent=m.senderName;time.dateTime=m.createdAt;time.textContent=new Date(m.createdAt).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});body.textContent=m.body;header.append(name,time);item.append(header,body);box.append(item);}if(atBottom||changed)box.scrollTop=box.scrollHeight;chat.lastSignature=signature;}
 chatEl('chatOlder').disabled=!data.hasMore;chatEl('chatOlder').onclick=()=>{chat.before=data.messages[0]?.id;chat.lastSignature='';chatLoad();};chatEl('chatLatest').hidden=!chat.before;
}
async function chatLoad(){if(!session||document.getElementById('tab-chat').classList.contains('hidden'))return;chatReset();const scope=chat.scope,request=++chat.request;try{const data=await chatCall('chatState',{conversationId:chat.selected,before:chat.before});if(scope!==chatScope()||request!==chat.request)return;chatRender(data);chatEl('chatStatus').textContent='';}catch(e){if(scope===chatScope()&&request===chat.request)chatEl('chatStatus').textContent=e.message;}}
chatEl('chatComposer').addEventListener('input',chatRemember);
chatEl('chatSend').onclick=async()=>{if(chat.sending||!chat.selected)return;const message=chatEl('chatComposer').value.trim();if(!message)return;const scope=chatScope(),conversationId=chat.selected;let attempt=chat.attempt;if(!attempt||attempt.message!==message||attempt.conversationId!==conversationId)attempt=chat.attempt={message,conversationId,clientId:crypto.randomUUID()};chat.sending=true;chatEl('chatSend').disabled=true;try{await chatCall('chatSend',attempt);if(scope!==chatScope())return;chat.attempt=null;if(chat.drafts.get(conversationId)?.trim()===message)chat.drafts.delete(conversationId);if(chat.selected===conversationId&&chatEl('chatComposer').value.trim()===message)chatEl('chatComposer').value='';chat.before=null;await chatLoad();}catch(e){if(scope===chatScope())chatEl('chatStatus').textContent=e.message;}finally{chat.sending=false;chatEl('chatSend').disabled=false;}};
chatEl('chatStartDM').onclick=async()=>{const target=chatEl('chatPerson').value;if(!target)return;const scope=chatScope();try{chatRemember();const data=await chatCall('chatOpenDM',{target});if(scope!==chatScope())return;chat.request++;chat.before=null;chatRender(data);}catch(e){if(scope===chatScope())chatEl('chatStatus').textContent=e.message;}};
chatEl('chatCreate').onclick=async()=>{const scope=chatScope();const data=await pxOwnerAction({title:'Create room channel',message:'Everyone in this room can read and post in this channel.',fields:[{name:'name',label:'Channel name',maxLength:40}],submitLabel:'Create channel',submit:fields=>chatCall('chatCreateChannel',{name:fields.name})});if(data&&scope===chatScope()){chat.request++;chatRemember();chat.before=null;chatRender(data);}};
chatEl('chatLatest').onclick=()=>{chat.before=null;chatLoad();};
document.querySelector('[data-tab="chat"]').addEventListener('click',()=>{chatReset();chatLoad();});
setInterval(()=>{if(!chat.before)chatLoad();},3000);
