import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import pg from 'pg';
import {PGlite} from '@electric-sql/pglite';
import {roomDay,roomDayBounds} from '../lib/operations.js';

test('room calendar boundaries include daylight-saving changes',()=>{
 const room={timezone:'America/Chicago'};
 assert.equal(roomDay(room,new Date('2026-09-29T01:00:00Z')),'2026-09-28');
 const spring=roomDayBounds(room,new Date('2026-03-08T18:00:00Z')),fall=roomDayBounds(room,new Date('2026-11-01T18:00:00Z'));
 assert.equal(spring.end-spring.start,23*3600000);assert.equal(fall.end-fall.start,25*3600000);
});

test('1.1 API regression: audit fixes and room chat',async t=>{
 const db=new PGlite();await db.exec(await fs.readFile(new URL('../schema.sql',import.meta.url),'utf8'));await db.exec('CREATE FUNCTION pg_advisory_xact_lock(bigint) RETURNS void LANGUAGE SQL AS $$ SELECT $$;');
 const query=(s,p=[])=>p.length?db.query(s,p):db.exec(s).then(r=>r.at(-1));pg.Pool=class{query(s,p=[]){return query(s,p)}async connect(){return {query,release(){}}}};
 process.env.POKEREX_ENABLE_DEMO='true';
 process.env.DATABASE_URL='postgres://disposable-test';
 const {default:handler}=await import('../api/app.js');
 const call=async body=>{let output,status=200;const res={setHeader(){},status(n){status=n;return this},json(v){output=v;return this}};await handler({method:'POST',body:{room:'4271',...body},query:{}},res);return {status,...output}};
 const owner=await call({action:'ownerLogin',orgCode:'DEMO',pin:'5555'});assert.equal(owner.status,200);
 const login=(name,pin,role='dealer')=>call({action:'roomLogin',name,pin,role});const manager=await login('George','2468','manager'),larry=await login('Larry','2222'),sarah=await login('Sarah','3333');
 const act=(s,action,b={})=>call({action,token:s.token,...b});
 await t.test('event date round-trip and reversed range rejection',async()=>{const r=await act(manager,'setEvent',{eventName:'Test',eventStart:'2026-10-27',eventEnd:'2026-10-29'});assert.equal(r.status,200);assert.equal(r.room.settings.eventStart,'2026-10-27');assert.equal(r.room.settings.eventEnd,'2026-10-29');assert.equal((await act(manager,'setEvent',{eventStart:'2026-10-29',eventEnd:'2026-10-27'})).status,400);});
 await t.test('conflicting approvals cannot reassign a filled shift',async()=>{let r=await act(manager,'addShift',{date:'2026-11-15',start:'09:00',end:'17:00',dealer:'OPEN'});const sh=r.room.schedule.find(s=>s.date==='2026-11-15');await act(larry,'claimShift',{shiftId:sh.id});r=await act(sarah,'claimShift',{shiftId:sh.id});const rs=r.room.swapRequests.filter(x=>x.shiftId===sh.id);assert.equal((await act(manager,'approveRequest',{requestId:rs.find(x=>x.requester==='Larry').id})).status,200);assert.equal((await act(manager,'approveRequest',{requestId:rs.find(x=>x.requester==='Sarah').id})).status,409);r=await act(manager,'state');assert.equal(r.room.schedule.find(x=>x.id===sh.id).dealer,'Larry');});
 await t.test('cancelled shift cannot be resurrected through approval',async()=>{let r=await act(manager,'addShift',{date:'2026-11-16',start:'09:00',end:'17:00',dealer:'Larry'});const sh=r.room.schedule.find(s=>s.date==='2026-11-16');r=await act(larry,'offerSwap',{shiftId:sh.id});const req=r.room.swapRequests.find(x=>x.shiftId===sh.id);await act(sarah,'acceptSwap',{requestId:req.id});await act(manager,'cancelShift',{shiftId:sh.id});assert.equal((await act(manager,'approveRequest',{requestId:req.id})).status,409);});
 await t.test('strict times and geofence coordinates',async()=>{assert.equal((await act(manager,'addShift',{date:'2026-11-17',start:'25:99',end:'30:90',dealer:'Larry'})).status,400);assert.equal((await act(manager,'setOperationsConfig',{geofenceEnabled:true,geofenceLat:'',geofenceLng:''})).status,400);assert.equal((await act(manager,'setOperationsConfig',{geofenceEnabled:true,geofenceLat:91,geofenceLng:0})).status,400);});
 await t.test('future clocks rejected; normal backdated clock sequence succeeds',async()=>{assert.equal((await act(manager,'managerClockIn',{name:'Larry',at:'2099-01-01T12:00:00Z'})).status,400);const at=new Date(Date.now()-7200000).toISOString();assert.equal((await act(manager,'managerClockIn',{name:'Larry',at})).status,200);assert.equal((await act(manager,'managerClockOut',{name:'Larry',at:new Date(Date.now()-10800000).toISOString()})).status,400);const out=await act(larry,'clockOut');assert.equal(out.status,200);assert.ok(out.room.timeEntries.every(x=>x.clockOut>x.clockIn));});
 await t.test('import rejects missing numbers and rolls back invalid batches',async()=>{assert.equal((await act(manager,'importDealers',{dealers:[{name:'Missing',dealerNumber:''}]})).status,400);const r=await act(manager,'importRosterSchedule',{rows:[{dealer:'Good row',dealerNumber:'971',date:'2026-11-20',start:'09:00'},{dealer:'Bad row',dealerNumber:'972',date:'2026-02-30',start:'09:00'}]});assert.equal(r.status,400);assert.equal((await db.query("SELECT count(*)::int AS n FROM room_members WHERE name IN ('Good row','Bad row')")).rows[0].n,0);});
 await t.test('renames preserve shift and time-entry ownership',async()=>{await db.query("UPDATE room_members SET dealer_number='118' WHERE name='Larry'");const r=await act(manager,'importRosterSchedule',{rows:[{dealer:'Larry Renamed',dealerNumber:'118'}]});assert.equal(r.status,200);assert.ok(r.room.schedule.some(x=>x.dealer==='Larry Renamed'));assert.ok(!r.room.schedule.some(x=>x.dealer==='Larry'));assert.ok(r.room.timeEntries.some(x=>x.name==='Larry Renamed'));});
 await t.test('late identity conflict rolls back earlier import writes',async()=>{const r=await act(manager,'importRosterSchedule',{rows:[{dealer:'Rollback Person',dealerNumber:'969'},{dealer:'George',dealerNumber:'118'}]});assert.equal(r.status,400);assert.equal((await db.query("SELECT count(*)::int AS n FROM room_members WHERE name='Rollback Person'")).rows[0].n,0);});
 await t.test('selected dealer role does not gain management permission',async()=>{const dealer=await login('George','1111');assert.equal((await act(dealer,'setRoom',{roomName:'Denied'})).status,403);});
 await t.test('disabled owner session loses access',async()=>{await call({action:'createOwner',orgCode:'DEMO',token:owner.token,name:'Second',pin:'876543'});const second=await call({action:'ownerLogin',orgCode:'DEMO',pin:'876543'}),target=second.owners.find(o=>o.name==='Second');await call({action:'setOwnerActive',orgCode:'DEMO',token:owner.token,ownerId:target.id,active:false});assert.equal((await call({action:'ownerBootstrap',orgCode:'DEMO',token:second.token})).status,401);assert.equal((await act(second,'state')).status,401);});
 await t.test('join requests use stable IDs and resolve once',async()=>{await call({action:'requestJoin',name:'Join One',pin:'4321'});await call({action:'requestJoin',name:'Join Two',pin:'4321'});let r=await act(manager,'state');const one=r.room.joinRequests.find(x=>x.name==='Join One'),two=r.room.joinRequests.find(x=>x.name==='Join Two');await act(manager,'denyJoin',{requestId:one.id});assert.equal((await act(manager,'approveJoin',{requestId:two.id})).status,200);assert.equal((await act(manager,'approveJoin',{requestId:two.id})).status,409);});
 let general,dm,privateChannel;
 await t.test('room channel message persists and retry is idempotent',async()=>{let r=await act(larry,'chatState');assert.equal(r.status,200);general=r.selected;const payload={conversationId:general,message:'Hello room',clientId:'test-message-0000001'};assert.equal((await act(larry,'chatSend',payload)).status,200);r=await act(larry,'chatSend',payload);assert.equal(r.messages.filter(m=>m.body==='Hello room').length,1);assert.equal((await act(larry,'chatSend',{...payload,message:'Changed'})).status,409);});
 await t.test('DM is visible only to its two participants',async()=>{let r=await act(larry,'chatState');const target=r.peers.find(p=>p.name==='Sarah').key;r=await act(larry,'chatOpenDM',{target});dm=r.selected;await act(larry,'chatSend',{conversationId:dm,message:'Private hello',clientId:'test-message-0000002'});assert.equal((await act(sarah,'chatState',{conversationId:dm})).messages[0].body,'Private hello');assert.equal((await act(manager,'chatState',{conversationId:dm})).status,403);assert.equal((await act(manager,'chatSend',{conversationId:dm,message:'Blocked',clientId:'test-message-0000003'})).status,403);});
 await t.test('channel creation and restricted channels require management',async()=>{assert.equal((await act(larry,'chatCreateChannel',{name:'unauthorized'})).status,403);const r=await act(manager,'chatCreateChannel',{name:'management',managersOnly:true});assert.equal(r.status,200);privateChannel=r.selected;assert.equal((await act(larry,'chatState',{conversationId:privateChannel})).status,403);});
 await t.test('chat rejects other-room conversations',async()=>{const {rows:[org]}=await db.query("SELECT id FROM organizations WHERE code='DEMO'");const {rows:[room]}=await db.query("INSERT INTO rooms(organization_id,code,room_name) VALUES($1,'9876','Other') RETURNING id",[org.id]);await db.query("INSERT INTO chat_conversations(id,room_id,kind,name,conversation_key) VALUES('foreign-chat',$1,'channel','general','channel:general')",[room.id]);assert.equal((await act(larry,'chatState',{conversationId:'foreign-chat'})).status,403);});
 await t.test('inactive recipients cannot receive new DMs',async()=>{await db.query("UPDATE room_members SET active=false WHERE name='Sarah'");assert.equal((await act(larry,'chatSend',{conversationId:dm,message:'Blocked inactive',clientId:'test-message-0000004'})).status,400);});
 await db.close();
});
